export const OPTIMIZATIONS = [
  { name: "Виртуализация", desc: "Отсечение невидимых нод", pros: "Снижает DOM-элементы", cons: "Может заметна подгрузка", impl: true },
  { name: "GPU-трансформации", desc: "translate3d", pros: "Плавное 60 FPS", cons: "Артефакты", impl: true },
  { name: "Throttle мыши", desc: "Ограничение частоты", pros: "Меньше лагов", cons: "Микро-задержка", impl: false },
  { name: "Batch-обновление RAF", desc: "Группировка изменений", pros: "Меньше перерисовок", cons: "Не мгновенный", impl: false },
  { name: "Кэш высоты", desc: "Сохранение высоты нод", pros: "Ускоряет расчёты", cons: "Инвалидация", impl: true },
  { name: "will-change", desc: "Предупреждение браузеру", pros: "Ускоряет анимации", cons: "Больше памяти", impl: true },
  { name: "Пассивные события", desc: "scroll/touch оптимизация", pros: "Плавный скролл", cons: "Старые браузеры", impl: false },
  { name: "Упрощение теней", desc: "Без теней при драге", pros: "Меньше перерисовка", cons: "Пропадают тени", impl: false },
  { name: "Отложенные связи", desc: "Связи с низким приоритетом", pros: "Быстрее перемещение", cons: "Линии отстают", impl: false },
  { name: "CSS containment", desc: "contain:layout", pros: "Изоляция макета", cons: "Обрезание контента", impl: true },
  { name: "Debounce рендера", desc: "Задержка рендера", pros: "Экономия ресурсов", cons: "Задержка", impl: false },
  { name: "Кэш getBoundingClientRect", desc: "Сохранение позиций", pros: "Быстрее расчёты", cons: "Обновление кэша", impl: false },
  { name: "Pointer-events линий", desc: "Настройка области линий", pros: "Быстрее клики", cons: "Незначительно", impl: true },
  { name: "Ленивые вычисления", desc: "setTimeout фоновые", pros: "UI отзывчив", cons: "Задержка", impl: false },
  { name: "Типизированные массивы", desc: "Float32Array", pros: "Мгновенный доступ", cons: "Сложно", impl: false },
  { name: "Ограничение истории", desc: "50->20 шагов", pros: "Меньше памяти", cons: "Меньше истории", impl: true },
  { name: "Кэш текста", desc: "Строки в кэше", pros: "Ускоряет поиск", cons: "Инвалидация", impl: false },
  { name: "WebGL-инстансинг", desc: "Тысячи нод через GPU", pros: "5000+ нод 60 FPS", cons: "Требует WebGL", impl: false },
  { name: "Качество дизайна", desc: "Снижение визуала", pros: "FPS до +300%", cons: "Визуал страдает", type: "slider", min: 0, max: 100, step: 1, default: 100, impl: true }
];
